#!/bin/bash
# Note: run as . ./start_script
#-----------------------------------------------------------------------------
# Start to display information to stdout
#------------------------------------------------------------------------------
clear
echo ESRV CONFIGURATION
echo ==================

#------------------------------------------------------------------------------
# Set paths
#------------------------------------------------------------------------------
ESRV_BINARY_PATH=/orssg-data/Development/iecsdk/_build/linux
ESRV_LIBRARY_PATH=/orssg-data/Development/iecsdk/_build/linux

#------------------------------------------------------------------------------
# Set esrv options.
# Note:
#    The grace time is required if the device to be used by esrv requires
#    a long start and configuration time.  If the time is not long enough
#    then this script may miss the output.  Other option is to loop
#    until the output file is created.
#------------------------------------------------------------------------------
ESRV_SHELL_VARIABLE_NAME=ESRV_GUID
ESRV_START_GRACE_TIME_IN_SECONDS=1
ENERGY_IN_HUNDREDS_OF_JOULE=0
ENERGY_IN_HUNDREDS_OF_KWH=2
POWER_IN_HUNDREDS_OF_W=6
#------------------------------------------------------------------------------
# Uncomment the right library - must exist 
#ESRV_LIBRARY=node_manager.so
#ESRV_LIBRARY=yokogawa_wt210.so
#ESRV_LIBRARY=yokogawa_wt230.so
#ESRV_LIBRARY=yokogawa_wt500.so
#ESRV_LIBRARY=yokogawa_wt3000.so
ESRV_LIBRARY=esrv_simulated_device.so


#------------------------------------------------------------------------------
# Create the gawk script to collect the GUID for our PL instance to read
# gawk script file is saved in gawk.script file
#------------------------------------------------------------------------------
echo "{ if(\$1==\"Using\") { print(substr(\$3, 2, length(\$3) - 2)); } }" > ./gawk.script

#------------------------------------------------------------------------------
# Start esrv instance
#------------------------------------------------------------------------------
echo Starting esrv instance...
$ESRV_BINARY_PATH/esrv --start --library $ESRV_LIBRARY_PATH/$ESRV_LIBRARY --shell > ./esrv.out &
echo "Pausing for $ESRV_START_GRACE_TIME_IN_SECONDS second(s)..."
sleep $ESRV_START_GRACE_TIME_IN_SECONDS

#------------------------------------------------------------------------------
# Collect the GUID for our PL instance created by this instance of
# linux_cpu_and_loadavg_info
#------------------------------------------------------------------------------
gawk -f ./gawk.script ./esrv.out > ./guid.out

#------------------------------------------------------------------------------
# Export ESRV_GUID variable
#------------------------------------------------------------------------------
GUID=`cat ./guid.out`
echo "$ESRV_SHELL_VARIABLE_NAME=$GUID" > ./set_guid.script
source ./set_guid.script

#-----------------------------------------------------------------------------
# Cleanup
#------------------------------------------------------------------------------
rm -rf ./gawk.script
rm -rf ./esrv.out
rm -rf ./guid.out
rm -rf ./set_guid.script

#-----------------------------------------------------------------------------
# Display information to stdout
#------------------------------------------------------------------------------
echo ------------------
echo "ESRV_SHELL VARIABLE = "[$ESRV_SHELL_VARIABLE_NAME]
echo "ESRV GUID           = "[$GUID]
echo "ESRV LIBRARY        = "[$ESRV_LIBRARY]
