#ifndef _CONSTANTES_H
#define _CONSTANTES_H

#define NOMBRE_DECIMALES 4
#define ECHELLE 10000.0 // 10^4

#define TAILLE_COMMANDE (400+1)
#define TAILLE_UUID (36+1)

#define TAILLE_TAMPON (500+1)

#define TAILLE_NOM_CONFIGURATION (200+1)
#define TAILLE_RACINE (200+1)
#define TAILLE_ADRESSE_MAC (16+1)
#define TAILLE_NOM_COMPTEUR (200+1)

typedef char NomConfiguration[TAILLE_NOM_CONFIGURATION];
typedef char AdresseMAC[TAILLE_ADRESSE_MAC];

#endif
